/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-serif)', 'Georgia', 'serif'],
        serif: ['var(--font-serif)', 'Georgia', 'serif'],
        mono: ['var(--font-jetbrains)', 'monospace'],
      },
      colors: {
        brand: {
          50:  '#eef6ff',
          100: '#daeaff',
          200: '#bdd9ff',
          300: '#90c0ff',
          400: '#5c9dff',
          500: '#3478f6',
          600: '#1d5fe8',
          700: '#1a4ec9',
          800: '#1c42a3',
          900: '#1c3a81',
          950: '#152552',
        },
        amber: {
          50:  '#fffbeb',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
        },
        gold: {
          50:   '#fbf6ea',
          100:  '#f5ead1',
          200:  '#ecd7a6',
          300:  '#e7c67a',
          400:  '#d9b766',
          500:  '#c99a45',
          600:  '#b3872f',
          700:  '#8f6a23',
          800:  '#6b4f1a',
          900:  '#4a3612',
        },
        surface: {
          0:   'var(--surface-0)',
          1:   'var(--surface-1)',
          2:   'var(--surface-2)',
          3:   'var(--surface-3)',
        },
        text: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted:     'var(--text-muted)',
        },
        border: {
          DEFAULT: 'var(--border)',
          subtle:  'var(--border-subtle)',
        },
        /* ── UI-3 semantic palette (Obsidian Gold) ──
           RGB-triplet tokens only defined under html[data-ui="ui3"], so
           ui1/ui2 stay untouched. */
        background:   'rgb(var(--u3-background) / <alpha-value>)',
        foreground:   'rgb(var(--u3-foreground) / <alpha-value>)',
        surface:      'rgb(var(--u3-surface) / <alpha-value>)',
        card:         { DEFAULT: 'rgb(var(--u3-card) / <alpha-value>)', foreground: 'rgb(var(--u3-card-foreground) / <alpha-value>)' },
        popover:      { DEFAULT: 'rgb(var(--u3-popover) / <alpha-value>)', foreground: 'rgb(var(--u3-popover-foreground) / <alpha-value>)' },
        primary:      { DEFAULT: 'rgb(var(--u3-primary) / <alpha-value>)', foreground: 'rgb(var(--u3-primary-foreground) / <alpha-value>)' },
        secondary:    { DEFAULT: 'rgb(var(--u3-secondary) / <alpha-value>)', foreground: 'rgb(var(--u3-secondary-foreground) / <alpha-value>)' },
        muted:        { DEFAULT: 'rgb(var(--u3-muted) / <alpha-value>)', foreground: 'rgb(var(--u3-muted-foreground) / <alpha-value>)' },
        accent:       { DEFAULT: 'rgb(var(--u3-accent) / <alpha-value>)', foreground: 'rgb(var(--u3-accent-foreground) / <alpha-value>)' },
        destructive:  { DEFAULT: 'rgb(var(--u3-destructive) / <alpha-value>)', foreground: 'rgb(var(--u3-destructive-foreground) / <alpha-value>)' },
        input:        'rgb(var(--u3-input) / <alpha-value>)',
        ring:         'rgb(var(--u3-ring) / <alpha-value>)',
      },
      boxShadow: {
        'soft-sm':  '0 1px 3px 0 rgb(0 0 0 / 0.07), 0 1px 2px -1px rgb(0 0 0 / 0.07)',
        'soft':     '0 4px 16px -2px rgb(0 0 0 / 0.08), 0 2px 8px -2px rgb(0 0 0 / 0.06)',
        'soft-lg':  '0 10px 40px -4px rgb(0 0 0 / 0.1), 0 4px 16px -4px rgb(0 0 0 / 0.08)',
        'soft-xl':  '0 24px 64px -8px rgb(0 0 0 / 0.12), 0 8px 24px -8px rgb(0 0 0 / 0.08)',
        'glow-blue':'0 0 24px rgb(52 120 246 / 0.25)',
        'glow-amber':'0 0 24px rgb(245 158 11 / 0.25)',
        'glow-gold': '0 0 24px rgb(217 183 102 / 0.35)',
        'glow-violet':'0 0 24px rgb(124 58 237 / 0.3)',
        'inner-sm': 'inset 0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'card':    '0 1px 2px rgb(34 42 66 / 0.05), 0 14px 34px -12px rgb(34 42 66 / 0.16), inset 0 1px 0 rgb(255 255 255 / 0.5)',
        'card-lg': '0 2px 6px rgb(34 42 66 / 0.07), 0 26px 60px -18px rgb(47 75 208 / 0.28), 0 16px 40px -18px rgb(34 42 66 / 0.22)',
        'gold':    '0 1px 0 rgb(255 255 255 / 0.5) inset, 0 12px 30px -10px rgb(179 135 47 / 0.6)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      animation: {
        'fade-in':       'fadeIn 0.4s ease-out',
        'fade-up':       'fadeUp 0.5s ease-out',
        'slide-down':    'slideDown 0.3s ease-out',
        'slide-up':      'slideUp 0.3s ease-out',
        'scale-in':      'scaleIn 0.2s ease-out',
        'float':         'float 6s ease-in-out infinite',
        'pulse-soft':    'pulseSoft 3s ease-in-out infinite',
        'shimmer':       'shimmer 2s linear infinite',
        'spin-slow':     'spin 8s linear infinite',
        'aurora':        'aurora 14s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' },                      to: { opacity: '1' } },
        fadeUp:    { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideUp:   { from: { opacity: '0', transform: 'translateY(8px)' },  to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:   { from: { opacity: '0', transform: 'scale(0.95)' },      to: { opacity: '1', transform: 'scale(1)' } },
        float:     { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
        pulseSoft: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.7' } },
        shimmer:   { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        aurora:    { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '50%': { transform: 'translate(4%,-3%) scale(1.06)' } },
      },
      backgroundImage: {
        'gradient-radial':   'radial-gradient(var(--tw-gradient-stops))',
        'gradient-mesh':     'radial-gradient(at 40% 20%, hsl(218,100%,95%) 0px, transparent 50%), radial-gradient(at 80% 0%, hsl(45,100%,95%) 0px, transparent 50%), radial-gradient(at 0% 50%, hsl(218,80%,96%) 0px, transparent 50%)',
        'gradient-mesh-dark':'radial-gradient(at 40% 20%, hsl(218,60%,12%) 0px, transparent 50%), radial-gradient(at 80% 0%, hsl(35,50%,10%) 0px, transparent 50%), radial-gradient(at 0% 50%, hsl(218,50%,10%) 0px, transparent 50%)',
      },
    },
  },
  plugins: [],
};
