export interface NcertChapter {
  id: string;
  title: string;
  slug: string;
}

export interface NcertSubject {
  id: string;
  name: string;
  bookName: string;
  slug: string;
  chapters: NcertChapter[];
}

export interface NcertClass {
  level: number;
  label: string;
  slug: string;
  subjects: NcertSubject[];
}

export const NCERT_SYLLABUS: NcertClass[] = [
  {
    level: 6,
    label: "Class 6",
    slug: "class-6",
    subjects: [
      {
        id: "maths",
        name: "Mathematics",
        bookName: "Ganita Prakash",
        slug: "mathematics",
        chapters: [
          { id: "ch-1", title: "Patterns in Mathematics", slug: "patterns-in-mathematics" },
          { id: "ch-2", title: "Lines and Angles", slug: "lines-and-angles" },
          { id: "ch-3", title: "Number Play", slug: "number-play" },
          { id: "ch-4", title: "Data Handling and Presentation", slug: "data-handling-and-presentation" },
          { id: "ch-5", title: "Prime Time", slug: "prime-time" },
          { id: "ch-6", title: "Equations", slug: "equations" },
          { id: "ch-7", title: "Ratio and Proportion", slug: "ratio-and-proportion" },
          { id: "ch-8", title: "Symmetry", slug: "symmetry" },
          { id: "ch-9", title: "Mensuration", slug: "mensuration" },
          { id: "ch-10", title: "Spoons and Forks", slug: "spoons-and-forks" },
        ],
      },
      {
        id: "science",
        name: "Science",
        bookName: "Curiosity",
        slug: "science",
        chapters: [
          { id: "ch-1", title: "The Wonderful World of Science", slug: "the-wonderful-world-of-science" },
          { id: "ch-2", title: "Diversity in the Living World", slug: "diversity-in-the-living-world" },
          { id: "ch-3", title: "The Plant Kingdom", slug: "the-plant-kingdom" },
          { id: "ch-4", title: "The Animal Kingdom", slug: "the-animal-kingdom" },
          { id: "ch-5", title: "Measurement of Length and Motion", slug: "measurement-of-length-and-motion" },
          { id: "ch-6", title: "Materials Around Us", slug: "materials-around-us" },
          { id: "ch-7", title: "Movement in Animals", slug: "movement-in-animals" },
          { id: "ch-8", title: "Light and Shadows", slug: "light-and-shadows" },
          { id: "ch-9", title: "The Earth in the Solar System", slug: "the-earth-in-the-solar-system" },
          { id: "ch-10", title: "A Journey Through Countries", slug: "a-journey-through-countries" },
          { id: "ch-11", title: "Food: Where Does It Come From?", slug: "food-where-does-it-come-from" },
          { id: "ch-12", title: "Getting to Know Plants", slug: "getting-to-know-plants" },
        ],
      },
      {
        id: "english",
        name: "English",
        bookName: "Poorvi",
        slug: "english",
        chapters: [
          { id: "u-1", title: "Unit 1 - A Tiny Need", slug: "unit-1-a-tiny-need" },
          { id: "u-2", title: "Unit 2 - Friendship", slug: "unit-2-friendship" },
          { id: "u-3", title: "Unit 3 - Nature's Beauty", slug: "unit-3-natures-beauty" },
          { id: "u-4", title: "Unit 4 - Helping Others", slug: "unit-4-helping-others" },
          { id: "u-5", title: "Unit 5 - Our Responsibilities", slug: "unit-5-our-responsibilities" },
          { id: "u-6", title: "Unit 6 - Imagination", slug: "unit-6-imagination" },
        ],
      },
      {
        id: "social-science",
        name: "Social Science",
        bookName: "Exploring Society: India and Beyond",
        slug: "social-science",
        chapters: [
          { id: "ch-1", title: "What is History?", slug: "what-is-history" },
          { id: "ch-2", title: "On the Trail of the Earliest People", slug: "on-the-trail-of-the-earliest-people" },
          { id: "ch-3", title: "From Gathering to Growing Food", slug: "from-gathering-to-growing-food" },
          { id: "ch-4", title: "In the Earliest Cities", slug: "in-the-earliest-cities" },
          { id: "ch-5", title: "What Books and Burials Tell Us", slug: "what-books-and-burials-tell-us" },
          { id: "ch-6", title: "Kingdoms, Kings and an Early Republic", slug: "kingdoms-kings-and-an-early-republic" },
          { id: "ch-7", title: "New Questions and Ideas", slug: "new-questions-and-ideas" },
          { id: "ch-8", title: "Ashoka, The Emperor Who Gave Up War", slug: "ashoka-the-emperor-who-gave-up-war" },
        ],
      },
      {
        id: "hindi",
        name: "Hindi",
        bookName: "Vasant",
        slug: "hindi",
        chapters: [
          { id: "ch-1", title: "\u0935\u0939 \u091a\u093f\u0921\u093c\u093f\u092f\u093e \u091c\u094b", slug: "vah-chidiya-jo" },
          { id: "ch-2", title: "\u092c\u091a\u094D\u0913\u0902 \u0915\u0947 \u092a\u094D\u0930\u093f\u092f \u0936\u094D\u0930\u0940 \u0915\u0947\u0936\u0935 \u0936\u0902\u0915\u0930 \u092a\u093e\u0902\u0921\u0947\u092f", slug: "bachchon-ki-priya-shri-kesav-shankar-pandey" },
          { id: "ch-3", title: "\u0928\u093e\u0926\u093e\u0928 \u0926\u094b\u0938\u094D\u0924", slug: "nadan-dost" },
          { id: "ch-4", title: "\u091a\u093e\u0901\u094D\u0926 \u0938\u0947 \u0925\u094b\u0921\u093c\u0940 \u0917\u092a\u094D\u092a", slug: "chand-se-thodi-gapp" },
          { id: "ch-5", title: "\u0905\u0915\u094D\u0937\u0930\u094b\u0902 \u0915\u0940 \u092f\u093e\u0924\u094D\u0930\u093e", slug: "aksharon-ki-yatra" },
        ],
      },
    ],
  },

  {
    level: 7,
    label: "Class 7",
    slug: "class-7",
    subjects: [
      {
        id: "maths",
        name: "Mathematics",
        bookName: "Ganita Prakash Part II",
        slug: "mathematics",
        chapters: [
          { id: "ch-1", title: "Integers", slug: "integers" },
          { id: "ch-2", title: "Fractions and Decimals", slug: "fractions-and-decimals" },
          { id: "ch-3", title: "Data Handling", slug: "data-handling" },
          { id: "ch-4", title: "Simple Equations", slug: "simple-equations" },
          { id: "ch-5", title: "Lines and Angles", slug: "lines-and-angles" },
          { id: "ch-6", title: "The Triangle and its Properties", slug: "the-triangle-and-its-properties" },
          { id: "ch-7", title: "Congruence of Triangles", slug: "congruence-of-triangles" },
          { id: "ch-8", title: "Comparing Quantities", slug: "comparing-quantities" },
        ],
      },
      {
        id: "science",
        name: "Science",
        bookName: "Curiosity",
        slug: "science",
        chapters: [
          { id: "ch-1", title: "Nutrition in Plants", slug: "nutrition-in-plants" },
          { id: "ch-2", title: "Nutrition in Animals", slug: "nutrition-in-animals" },
          { id: "ch-3", title: "Fibre to Fabric", slug: "fibre-to-fabric" },
          { id: "ch-4", title: "Heat", slug: "heat" },
          { id: "ch-5", title: "Acids, Bases and Salts", slug: "acids-bases-and-salts" },
          { id: "ch-6", title: "Physical and Chemical Changes", slug: "physical-and-chemical-changes" },
          { id: "ch-7", title: "Weather, Climate and Adaptations", slug: "weather-climate-and-adaptations" },
          { id: "ch-8", title: "Winds, Storms and Cyclones", slug: "winds-storms-and-cyclones" },
          { id: "ch-9", title: "Soil", slug: "soil" },
          { id: "ch-10", title: "Respiration in Organisms", slug: "respiration-in-organisms" },
          { id: "ch-11", title: "Transportation in Animals and Plants", slug: "transportation-in-animals-and-plants" },
          { id: "ch-12", title: "Reproduction in Plants", slug: "reproduction-in-plants" },
        ],
      },
      {
        id: "english",
        name: "English",
        bookName: "Poorvi",
        slug: "english",
        chapters: [
          { id: "u-1", title: "Unit 1 - A Day in the Life of", slug: "unit-1-a-day-in-the-life-of" },
          { id: "u-2", title: "Unit 2 - Love and Care", slug: "unit-2-love-and-care" },
          { id: "u-3", title: "Unit 3 - Travel and Adventure", slug: "unit-3-travel-and-adventure" },
          { id: "u-4", title: "Unit 4 - Values and Virtues", slug: "unit-4-values-and-virtues" },
          { id: "u-5", title: "Unit 5 - Our Environment", slug: "unit-5-our-environment" },
          { id: "u-6", title: "Unit 6 - Science and Technology", slug: "unit-6-science-and-technology" },
        ],
      },
      {
        id: "social-science",
        name: "Social Science",
        bookName: "Exploring Society: India and Beyond",
        slug: "social-science",
        chapters: [
          { id: "ch-1", title: "Tracing Changes Through a Thousand Years", slug: "tracing-changes-through-a-thousand-years" },
          { id: "ch-2", title: "New Kings and Kingdoms", slug: "new-kings-and-kingdoms" },
          { id: "ch-3", title: "The Delhi Sultans", slug: "the-delhi-sultans" },
          { id: "ch-4", title: "The Mughal Empire", slug: "the-mughal-empire" },
          { id: "ch-5", title: "Rulers and Buildings", slug: "rulers-and-buildings" },
          { id: "ch-6", title: "Towns, Traders and Craftspersons", slug: "towns-traders-and-craftspersons" },
          { id: "ch-7", title: "Tribes, Nomads and Settled Communities", slug: "tribes-nomads-and-settled-communities" },
          { id: "ch-8", title: "Devotional Paths to the Divine", slug: "devotional-paths-to-the-divine" },
        ],
      },
      {
        id: "hindi",
        name: "Hindi",
        bookName: "Vasant",
        slug: "hindi",
        chapters: [
          { id: "ch-1", title: "Himachal Ki Betiyan", slug: "himachal-ki-betiyan" },
          { id: "ch-2", title: "Babila", slug: "babilia" },
          { id: "ch-3", title: "Mithaiwala", slug: "mithaiwala" },
          { id: "ch-4", title: "Reedh Ki Haddi", slug: "reedh-ki-haddi" },
        ],
      },
    ],
  },

  {
    level: 8,
    label: "Class 8",
    slug: "class-8",
    subjects: [
      {
        id: "maths",
        name: "Mathematics",
        bookName: "Ganita Prakash",
        slug: "mathematics",
        chapters: [
          { id: "ch-1", title: "Rational Numbers", slug: "rational-numbers" },
          { id: "ch-2", title: "Linear Equations in One Variable", slug: "linear-equations-in-one-variable" },
          { id: "ch-3", title: "Understanding Quadrilaterals", slug: "understanding-quadrilaterals" },
          { id: "ch-4", title: "Data Handling", slug: "data-handling" },
          { id: "ch-5", title: "Squares and Square Roots", slug: "squares-and-square-roots" },
          { id: "ch-6", title: "Cubes and Cube Roots", slug: "cubes-and-cube-roots" },
          { id: "ch-7", title: "Comparing Quantities", slug: "comparing-quantities" },
          { id: "ch-8", title: "Mensuration", slug: "mensuration" },
          { id: "ch-9", title: "Exponents and Powers", slug: "exponents-and-powers" },
          { id: "ch-10", title: "Direct and Inverse Proportions", slug: "direct-and-inverse-proportions" },
        ],
      },
      {
        id: "science",
        name: "Science",
        bookName: "Curiosity",
        slug: "science",
        chapters: [
          { id: "ch-1", title: "Crop Production and Management", slug: "crop-production-and-management" },
          { id: "ch-2", title: "Microorganisms: Friends and Foes", slug: "microorganisms-friends-and-foes" },
          { id: "ch-3", title: "Synthetic Fibres and Plastics", slug: "synthetic-fibres-and-plastics" },
          { id: "ch-4", title: "Materials: Metals and Non-Metals", slug: "materials-metals-and-non-metals" },
          { id: "ch-5", title: "Coal and Petroleum", slug: "coal-and-petroleum" },
          { id: "ch-6", title: "Combustion and Flame", slug: "combustion-and-flame" },
          { id: "ch-7", title: "Conservation of Plants and Animals", slug: "conservation-of-plants-and-animals" },
          { id: "ch-8", title: "Cell - Structure and Functions", slug: "cell-structure-and-functions" },
          { id: "ch-9", title: "Reproduction in Animals", slug: "reproduction-in-animals" },
          { id: "ch-10", title: "Reaching the Age of Adolescence", slug: "reaching-the-age-of-adolescence" },
          { id: "ch-11", title: "Force and Pressure", slug: "force-and-pressure" },
          { id: "ch-12", title: "Friction", slug: "friction" },
        ],
      },
      {
        id: "english",
        name: "English",
        bookName: "Poorvi",
        slug: "english",
        chapters: [
          { id: "u-1", title: "Unit 1 - Role Models", slug: "unit-1-role-models" },
          { id: "u-2", title: "Unit 2 - The Joy of Giving", slug: "unit-2-the-joy-of-giving" },
          { id: "u-3", title: "Unit 3 - Exploring Nature", slug: "unit-3-exploring-nature" },
          { id: "u-4", title: "Unit 4 - Creativity and Innovation", slug: "unit-4-creativity-and-innovation" },
          { id: "u-5", title: "Unit 5 - Courage and Determination", slug: "unit-5-courage-and-determination" },
          { id: "u-6", title: "Unit 6 - Global Citizenship", slug: "unit-6-global-citizenship" },
        ],
      },
      {
        id: "social-science",
        name: "Social Science",
        bookName: "Exploring Society: India and Beyond",
        slug: "social-science",
        chapters: [
          { id: "ch-1", title: "How, When and Where", slug: "how-when-and-where" },
          { id: "ch-2", title: "From Trade to Territory", slug: "from-trade-to-territory" },
          { id: "ch-3", title: "Ruling the Countryside", slug: "ruling-the-countryside" },
          { id: "ch-4", title: "Tribals, Dikus and the Vision of a Golden Age", slug: "tribals-dikus-and-the-vision-of-a-golden-age" },
          { id: "ch-5", title: "When People Rebel", slug: "when-people-rebel" },
          { id: "ch-6", title: "Weavers, Iron Smelters and Factory Owners", slug: "weavers-iron-smelters-and-factory-owners" },
          { id: "ch-7", title: "Civilising the Native, Educating the Nation", slug: "civilising-the-native-educating-the-nation" },
          { id: "ch-8", title: "Women, Caste and Reform", slug: "women-caste-and-reform" },
        ],
      },
      {
        id: "hindi",
        name: "Hindi",
        bookName: "Vasant",
        slug: "hindi",
        chapters: [
          { id: "ch-1", title: "Samudra Ka Mahatva", slug: "samudra-ka-mahatva" },
          { id: "ch-2", title: "Devang Ka Deva", slug: "devang-ka-deva" },
          { id: "ch-3", title: "Jar Ka Phool", slug: "jar-ka-phool" },
          { id: "ch-4", title: "Samundra Ki Patha", slug: "samundra-ki-patha" },
          { id: "ch-5", title: "Drishad Ka Yapjoo", slug: "drishad-ka-yapjoo" },
        ],
      },
    ],
  },

  {
    level: 9,
    label: "Class 9",
    slug: "class-9",
    subjects: [
      {
        id: "maths",
        name: "Mathematics",
        bookName: "Ganita Manjari Part I",
        slug: "mathematics",
        chapters: [
          { id: "ch-1", title: "Number Systems", slug: "number-systems" },
          { id: "ch-2", title: "Polynomials", slug: "polynomials" },
          { id: "ch-3", title: "Coordinate Geometry", slug: "coordinate-geometry" },
          { id: "ch-4", title: "Linear Equations in Two Variables", slug: "linear-equations-in-two-variables" },
          { id: "ch-5", title: "Introduction to Euclid's Geometry", slug: "introduction-to-euclids-geometry" },
          { id: "ch-6", title: "Lines and Angles", slug: "lines-and-angles" },
          { id: "ch-7", title: "Triangles", slug: "triangles" },
          { id: "ch-8", title: "Quadrilaterals", slug: "quadrilaterals" },
        ],
      },
      {
        id: "science",
        name: "Science",
        bookName: "Exploration",
        slug: "science",
        chapters: [
          { id: "ch-1", title: "Matter in Our Surroundings", slug: "matter-in-our-surroundings" },
          { id: "ch-2", title: "Is Matter Around Us Pure?", slug: "is-matter-around-us-pure" },
          { id: "ch-3", title: "Atoms and Molecules", slug: "atoms-and-molecules" },
          { id: "ch-4", title: "Structure of the Atom", slug: "structure-of-the-atom" },
          { id: "ch-5", title: "The Fundamental Unit of Life", slug: "the-fundamental-unit-of-life" },
          { id: "ch-6", title: "Tissues", slug: "tissues" },
          { id: "ch-7", title: "Diversity in Living Organisms", slug: "diversity-in-living-organisms" },
          { id: "ch-8", title: "Motion", slug: "motion" },
          { id: "ch-9", title: "Force and Laws of Motion", slug: "force-and-laws-of-motion" },
          { id: "ch-10", title: "Gravitation", slug: "gravitation" },
          { id: "ch-11", title: "Work and Energy", slug: "work-and-energy" },
          { id: "ch-12", title: "Sound", slug: "sound" },
          { id: "ch-13", title: "Why Do We Fall Ill?", slug: "why-do-we-fall-ill" },
        ],
      },
      {
        id: "english",
        name: "English",
        bookName: "Kaveri",
        slug: "english",
        chapters: [
          { id: "ch-1", title: "The Fun They Had", slug: "the-fun-they-had" },
          { id: "ch-2", title: "The Sound of Music", slug: "the-sound-of-music" },
          { id: "ch-3", title: "The Little Girl", slug: "the-little-girl" },
          { id: "ch-4", title: "A Truly Beautiful Mind", slug: "a-truly-beautiful-mind" },
          { id: "ch-5", title: "The Snake and the Mirror", slug: "the-snake-and-the-mirror" },
          { id: "ch-6", title: "My Childhood", slug: "my-childhood" },
          { id: "ch-7", title: "Packing", slug: "packing" },
          { id: "ch-8", title: "Reach for the Top", slug: "reach-for-the-top" },
        ],
      },
      {
        id: "social-science",
        name: "Social Science",
        bookName: "Understanding Society",
        slug: "social-science",
        chapters: [
          { id: "ch-1", title: "What is History? How do we Study it?", slug: "what-is-history-how-do-we-study-it" },
          { id: "ch-2", title: "On the Trail of the Earliest People", slug: "on-the-trail-of-the-earliest-people" },
          { id: "ch-3", title: "From Gathering to Growing Food", slug: "from-gathering-to-growing-food" },
          { id: "ch-4", title: "In the Earliest Cities", slug: "in-the-earliest-cities" },
          { id: "ch-5", title: "What Books and Burials Tell Us", slug: "what-books-and-burials-tell-us" },
          { id: "ch-6", title: "Kingdoms, Kings and an Early Republic", slug: "kingdoms-kings-and-an-early-republic" },
          { id: "ch-7", title: "New Questions and Ideas", slug: "new-questions-and-ideas" },
          { id: "ch-8", title: "Ashoka, The Emperor Who Gave Up War", slug: "ashoka-the-emperor-who-gave-up-war" },
          { id: "ch-9", title: "India's Size and Location", slug: "indias-size-and-location" },
        ],
      },
      {
        id: "hindi",
        name: "Hindi",
        bookName: "Kshitij",
        slug: "hindi",
        chapters: [
          { id: "ch-1", title: "Dosta Ka Chitra", slug: "dosta-ka-chitra" },
          { id: "ch-2", title: "Sinha Ka Mahatva", slug: "sinha-ka-mahatva" },
          { id: "ch-3", title: "Apnita Ki Sath", slug: "apnita-ki-sath" },
          { id: "ch-4", title: "Chandrashekhar Ke Darshan", slug: "chandrashekhar-ke-darshan" },
          { id: "ch-5", title: "Mera Vapisa", slug: "mera-vapisa" },
        ],
      },
    ],
  },

  {
    level: 10,
    label: "Class 10",
    slug: "class-10",
    subjects: [
      {
        id: "maths",
        name: "Mathematics",
        bookName: "Ganita Prakash Part II",
        slug: "mathematics",
        chapters: [
          { id: "ch-1", title: "Real Numbers", slug: "real-numbers" },
          { id: "ch-2", title: "Polynomials", slug: "polynomials" },
          { id: "ch-3", title: "Pair of Linear Equations in Two Variables", slug: "pair-of-linear-equations-in-two-variables" },
          { id: "ch-4", title: "Quadratic Equations", slug: "quadratic-equations" },
          { id: "ch-5", title: "Arithmetic Progressions", slug: "arithmetic-progressions" },
          { id: "ch-6", title: "Triangles", slug: "triangles" },
          { id: "ch-7", title: "Coordinate Geometry", slug: "coordinate-geometry" },
          { id: "ch-8", title: "Introduction to Trigonometry", slug: "introduction-to-trigonometry" },
          { id: "ch-9", title: "Some Applications of Trigonometry", slug: "some-applications-of-trigonometry" },
          { id: "ch-10", title: "Circles", slug: "circles" },
          { id: "ch-11", title: "Areas Related to Circles", slug: "areas-related-to-circles" },
          { id: "ch-12", title: "Surface Areas and Volumes", slug: "surface-areas-and-volumes" },
          { id: "ch-13", title: "Statistics", slug: "statistics" },
          { id: "ch-14", title: "Probability", slug: "probability" },
        ],
      },
      {
        id: "science",
        name: "Science",
        bookName: "Curiosity",
        slug: "science",
        chapters: [
          { id: "ch-1", title: "Chemical Reactions and Equations", slug: "chemical-reactions-and-equations" },
          { id: "ch-2", title: "Acids, Bases and Salts", slug: "acids-bases-and-salts" },
          { id: "ch-3", title: "Metals and Non-Metals", slug: "metals-and-non-metals" },
          { id: "ch-4", title: "Carbon and its Compounds", slug: "carbon-and-its-compounds" },
          { id: "ch-5", title: "Life Processes", slug: "life-processes" },
          { id: "ch-6", title: "Control and Coordination", slug: "control-and-coordination" },
          { id: "ch-7", title: "How do Organisms Reproduce?", slug: "how-do-organisms-reproduce" },
          { id: "ch-8", title: "Heredity", slug: "heredity" },
          { id: "ch-9", title: "Light - Reflection and Refraction", slug: "light-reflection-and-refraction" },
          { id: "ch-10", title: "The Human Eye and the Colourful World", slug: "the-human-eye-and-the-colourful-world" },
          { id: "ch-11", title: "Electricity", slug: "electricity" },
          { id: "ch-12", title: "Magnetic Effects of Electric Current", slug: "magnetic-effects-of-electric-current" },
          { id: "ch-13", title: "Our Environment", slug: "our-environment" },
        ],
      },
      {
        id: "english",
        name: "English",
        bookName: "First Flight",
        slug: "english",
        chapters: [
          { id: "ch-1", title: "A Letter to God", slug: "a-letter-to-god" },
          { id: "ch-2", title: "Nelson Mandela: Long Walk to Freedom", slug: "nelson-mandela-long-walk-to-freedom" },
          { id: "ch-3", title: "Two Stories about Flying", slug: "two-stories-about-flying" },
          { id: "ch-4", title: "From the Diary of Anne Frank", slug: "from-the-diary-of-anne-frank" },
          { id: "ch-5", title: "The Hundred Dresses - I", slug: "the-hundred-dresses-i" },
          { id: "ch-6", title: "The Hundred Dresses - II", slug: "the-hundred-dresses-ii" },
          { id: "ch-7", title: "Glimpses of India", slug: "glimpses-of-india" },
          { id: "ch-8", title: "Mijbil the Otter", slug: "mijbil-the-otter" },
          { id: "ch-9", title: "Madam Rides the Bus", slug: "madam-rides-the-bus" },
          { id: "ch-10", title: "The Sermon at Benares", slug: "the-sermon-at-benares" },
        ],
      },
      {
        id: "social-science",
        name: "Social Science",
        bookName: "Understanding Society",
        slug: "social-science",
        chapters: [
          { id: "ch-1", title: "The Rise of Nationalism in Europe", slug: "the-rise-of-nationalism-in-europe" },
          { id: "ch-2", title: "Nationalism in India", slug: "nationalism-in-india" },
          { id: "ch-3", title: "The Making of a Global World", slug: "the-making-of-a-global-world" },
          { id: "ch-4", title: "The Age of Industrialisation", slug: "the-age-of-industrialisation" },
          { id: "ch-5", title: "Print Culture and the Modern World", slug: "print-culture-and-the-modern-world" },
          { id: "ch-6", title: "Resources and Development", slug: "resources-and-development" },
          { id: "ch-7", title: "Forest and Wildlife Resources", slug: "forest-and-wildlife-resources" },
          { id: "ch-8", title: "Water Resources", slug: "water-resources" },
          { id: "ch-9", title: "Agriculture", slug: "agriculture" },
        ],
      },
      {
        id: "hindi",
        name: "Hindi",
        bookName: "Kshitij",
        slug: "hindi",
        chapters: [
          { id: "ch-1", title: "Surdas Ki Padavali", slug: "surdas-ki-padavali" },
          { id: "ch-2", title: "Ram-Vinay-Varman Kavitavali", slug: "ram-vinay-varman-kavitavali" },
          { id: "ch-3", title: "Sri Hari Katha", slug: "sri-hari-katha" },
          { id: "ch-4", title: "Samvet Manthan", slug: "samvet-manthan" },
          { id: "ch-5", title: "Aatmaparichay", slug: "aatmaparichay" },
          { id: "ch-6", title: "Is Jal Pralay Mein Bhi", slug: "is-jal-pralay-mein-bhi" },
          { id: "ch-7", title: "Topi Wala Larka", slug: "topi-wala-larka" },
          { id: "ch-8", title: "Chhaya Mritak Ki Dhara", slug: "chhaya-mritak-ki-dhara" },
        ],
      },
    ],
  },

  {
    level: 11,
    label: "Class 11",
    slug: "class-11",
    subjects: [
      {
        id: "physics",
        name: "Physics",
        bookName: "Physics Part I",
        slug: "physics",
        chapters: [
          { id: "ch-1", title: "Physical World", slug: "physical-world" },
          { id: "ch-2", title: "Units and Measurements", slug: "units-and-measurements" },
          { id: "ch-3", title: "Motion in a Straight Line", slug: "motion-in-a-straight-line" },
          { id: "ch-4", title: "Motion in a Plane", slug: "motion-in-a-plane" },
          { id: "ch-5", title: "Laws of Motion", slug: "laws-of-motion" },
          { id: "ch-6", title: "Work, Energy and Power", slug: "work-energy-and-power" },
          { id: "ch-7", title: "System of Particles and Rotational Motion", slug: "system-of-particles-and-rotational-motion" },
          { id: "ch-8", title: "Gravitation", slug: "gravitation" },
          { id: "ch-9", title: "Mechanical Properties of Solids", slug: "mechanical-properties-of-solids" },
          { id: "ch-10", title: "Mechanical Properties of Fluids", slug: "mechanical-properties-of-fluids" },
          { id: "ch-11", title: "Thermal Properties of Matter", slug: "thermal-properties-of-matter" },
          { id: "ch-12", title: "Thermodynamics", slug: "thermodynamics" },
          { id: "ch-13", title: "Kinetic Theory", slug: "kinetic-theory" },
          { id: "ch-14", title: "Oscillations", slug: "oscillations" },
          { id: "ch-15", title: "Waves", slug: "waves" },
        ],
      },
      {
        id: "chemistry",
        name: "Chemistry",
        bookName: "Chemistry Part I",
        slug: "chemistry",
        chapters: [
          { id: "ch-1", title: "Some Basic Concepts of Chemistry", slug: "some-basic-concepts-of-chemistry" },
          { id: "ch-2", title: "Structure of Atom", slug: "structure-of-atom" },
          { id: "ch-3", title: "Classification of Elements and Periodicity", slug: "classification-of-elements-and-periodicity" },
          { id: "ch-4", title: "Chemical Bonding and Molecular Structure", slug: "chemical-bonding-and-molecular-structure" },
          { id: "ch-5", title: "States of Matter", slug: "states-of-matter" },
          { id: "ch-6", title: "Thermodynamics", slug: "thermodynamics" },
          { id: "ch-7", title: "Equilibrium", slug: "equilibrium" },
          { id: "ch-8", title: "Redox Reactions", slug: "redox-reactions" },
          { id: "ch-9", title: "Hydrogen", slug: "hydrogen" },
          { id: "ch-10", title: "The s-Block Elements", slug: "the-s-block-elements" },
        ],
      },
      {
        id: "biology",
        name: "Biology",
        bookName: "Biology Part I & II",
        slug: "biology",
        chapters: [
          { id: "ch-1", title: "The Living World", slug: "the-living-world" },
          { id: "ch-2", title: "Biological Classification", slug: "biological-classification" },
          { id: "ch-3", title: "Plant Kingdom", slug: "plant-kingdom" },
          { id: "ch-4", title: "Animal Kingdom", slug: "animal-kingdom" },
          { id: "ch-5", title: "Morphology of Flowering Plants", slug: "morphology-of-flowering-plants" },
          { id: "ch-6", title: "Anatomy of Flowering Plants", slug: "anatomy-of-flowering-plants" },
          { id: "ch-7", title: "Structural Organisation in Animals", slug: "structural-organisation-in-animals" },
          { id: "ch-8", title: "Cell: The Unit of Life", slug: "cell-the-unit-of-life" },
          { id: "ch-9", title: "Biomolecules", slug: "biomolecules" },
          { id: "ch-10", title: "Cell Cycle and Cell Division", slug: "cell-cycle-and-cell-division" },
          { id: "ch-11", title: "Transport in Plants", slug: "transport-in-plants" },
          { id: "ch-12", title: "Mineral Nutrition", slug: "mineral-nutrition" },
          { id: "ch-13", title: "Photosynthesis in Higher Plants", slug: "photosynthesis-in-higher-plants" },
          { id: "ch-14", title: "Respiration in Plants", slug: "respiration-in-plants" },
          { id: "ch-15", title: "Plant Growth and Development", slug: "plant-growth-and-development" },
          { id: "ch-16", title: "Digestion and Absorption", slug: "digestion-and-absorption" },
          { id: "ch-17", title: "Breathing and Exchange of Gases", slug: "breathing-and-exchange-of-gases" },
          { id: "ch-18", title: "Body Fluids and Circulation", slug: "body-fluids-and-circulation" },
          { id: "ch-19", title: "Excretory Products and their Elimination", slug: "excretory-products-and-their-elimination" },
          { id: "ch-20", title: "Locomotion and Movement", slug: "locomotion-and-movement" },
          { id: "ch-21", title: "Neural Control and Coordination", slug: "neural-control-and-coordination" },
          { id: "ch-22", title: "Chemical Coordination and Integration", slug: "chemical-coordination-and-integration" },
        ],
      },
      {
        id: "maths",
        name: "Mathematics",
        bookName: "Mathematics Part I & II",
        slug: "mathematics",
        chapters: [
          { id: "ch-1", title: "Sets", slug: "sets" },
          { id: "ch-2", title: "Relations and Functions", slug: "relations-and-functions" },
          { id: "ch-3", title: "Trigonometric Functions", slug: "trigonometric-functions" },
          { id: "ch-4", title: "Principle of Mathematical Induction", slug: "principle-of-mathematical-induction" },
          { id: "ch-5", title: "Complex Numbers and Quadratic Equations", slug: "complex-numbers-and-quadratic-equations" },
          { id: "ch-6", title: "Linear Inequalities", slug: "linear-inequalities" },
          { id: "ch-7", title: "Permutations and Combinations", slug: "permutations-and-combinations" },
          { id: "ch-8", title: "Binomial Theorem", slug: "binomial-theorem" },
          { id: "ch-9", title: "Sequences and Series", slug: "sequences-and-series" },
          { id: "ch-10", title: "Straight Lines", slug: "straight-lines" },
          { id: "ch-11", title: "Conic Sections", slug: "conic-sections" },
          { id: "ch-12", title: "Introduction to Three Dimensional Geometry", slug: "introduction-to-three-dimensional-geometry" },
          { id: "ch-13", title: "Limits and Derivatives", slug: "limits-and-derivatives" },
          { id: "ch-14", title: "Mathematical Reasoning", slug: "mathematical-reasoning" },
          { id: "ch-15", title: "Statistics", slug: "statistics" },
          { id: "ch-16", title: "Probability", slug: "probability" },
        ],
      },
      {
        id: "english",
        name: "English",
        bookName: "Hornbill",
        slug: "english",
        chapters: [
          { id: "ch-1", title: "The Portrait of a Lady", slug: "the-portrait-of-a-lady" },
          { id: "ch-2", title: "We're Not Afraid to Die... if We Can All Be Together", slug: "were-not-afraid-to-die-if-we-can-all-be-together" },
          { id: "ch-3", title: "Discovering Tut: the Saga Continues", slug: "discovering-tut-the-saga-continues" },
          { id: "ch-4", title: "The Laburnum Top", slug: "the-laburnum-top" },
          { id: "ch-5", title: "The Voice of the Rain", slug: "the-voice-of-the-rain" },
          { id: "ch-6", title: "Childhood", slug: "childhood" },
          { id: "ch-7", title: "Father to Son", slug: "father-to-son" },
          { id: "ch-8", title: "The Adventure", slug: "the-adventure" },
        ],
      },
    ],
  },

  {
    level: 12,
    label: "Class 12",
    slug: "class-12",
    subjects: [
      {
        id: "physics",
        name: "Physics",
        bookName: "Physics Part I & II",
        slug: "physics",
        chapters: [
          { id: "ch-1", title: "Electric Charges and Fields", slug: "electric-charges-and-fields" },
          { id: "ch-2", title: "Electrostatic Potential and Capacitance", slug: "electrostatic-potential-and-capacitance" },
          { id: "ch-3", title: "Current Electricity", slug: "current-electricity" },
          { id: "ch-4", title: "Moving Charges and Magnetism", slug: "moving-charges-and-magnetism" },
          { id: "ch-5", title: "Magnetism and Matter", slug: "magnetism-and-matter" },
          { id: "ch-6", title: "Electromagnetic Induction", slug: "electromagnetic-induction" },
          { id: "ch-7", title: "Alternating Current", slug: "alternating-current" },
          { id: "ch-8", title: "Electromagnetic Waves", slug: "electromagnetic-waves" },
          { id: "ch-9", title: "Ray Optics and Optical Instruments", slug: "ray-optics-and-optical-instruments" },
          { id: "ch-10", title: "Wave Optics", slug: "wave-optics" },
          { id: "ch-11", title: "Dual Nature of Radiation and Matter", slug: "dual-nature-of-radiation-and-matter" },
          { id: "ch-12", title: "Atoms", slug: "atoms" },
          { id: "ch-13", title: "Nuclei", slug: "nuclei" },
          { id: "ch-14", title: "Semiconductor Electronics", slug: "semiconductor-electronics" },
        ],
      },
      {
        id: "chemistry",
        name: "Chemistry",
        bookName: "Chemistry Part I & II",
        slug: "chemistry",
        chapters: [
          { id: "ch-1", title: "The Solid State", slug: "the-solid-state" },
          { id: "ch-2", title: "Solutions", slug: "solutions" },
          { id: "ch-3", title: "Electrochemistry", slug: "electrochemistry" },
          { id: "ch-4", title: "Chemical Kinetics", slug: "chemical-kinetics" },
          { id: "ch-5", title: "Surface Chemistry", slug: "surface-chemistry" },
          { id: "ch-6", title: "General Principles and Processes of Isolation of Elements", slug: "general-principles-and-processes-of-isolation-of-elements" },
          { id: "ch-7", title: "The p-Block Elements", slug: "the-p-block-elements" },
          { id: "ch-8", title: "The d- and f-Block Elements", slug: "the-d-and-f-block-elements" },
          { id: "ch-9", title: "Coordination Compounds", slug: "coordination-compounds" },
          { id: "ch-10", title: "Haloalkanes and Haloarenes", slug: "haloalkanes-and-haloarenes" },
        ],
      },
      {
        id: "biology",
        name: "Biology",
        bookName: "Biology Part I & II",
        slug: "biology",
        chapters: [
          { id: "ch-1", title: "Reproduction in Organisms", slug: "reproduction-in-organisms" },
          { id: "ch-2", title: "Sexual Reproduction in Flowering Plants", slug: "sexual-reproduction-in-flowering-plants" },
          { id: "ch-3", title: "Human Reproduction", slug: "human-reproduction" },
          { id: "ch-4", title: "Reproductive Health", slug: "reproductive-health" },
          { id: "ch-5", title: "Principles of Inheritance and Variation", slug: "principles-of-inheritance-and-variation" },
          { id: "ch-6", title: "Molecular Basis of Inheritance", slug: "molecular-basis-of-inheritance" },
          { id: "ch-7", title: "Evolution", slug: "evolution" },
          { id: "ch-8", title: "Human Health and Disease", slug: "human-health-and-disease" },
          { id: "ch-9", title: "Strategies for Enhancement in Food Production", slug: "strategies-for-enhancement-in-food-production" },
          { id: "ch-10", title: "Microbes in Human Welfare", slug: "microbes-in-human-welfare" },
          { id: "ch-11", title: "Biotechnology: Principles and Processes", slug: "biotechnology-principles-and-processes" },
          { id: "ch-12", title: "Biotechnology and its Applications", slug: "biotechnology-and-its-applications" },
          { id: "ch-13", title: "Organisms and Populations", slug: "organisms-and-populations" },
        ],
      },
      {
        id: "maths",
        name: "Mathematics",
        bookName: "Mathematics Part I & II",
        slug: "mathematics",
        chapters: [
          { id: "ch-1", title: "Relations and Functions", slug: "relations-and-functions" },
          { id: "ch-2", title: "Inverse Trigonometric Functions", slug: "inverse-trigonometric-functions" },
          { id: "ch-3", title: "Matrices", slug: "matrices" },
          { id: "ch-4", title: "Determinants", slug: "determinants" },
          { id: "ch-5", title: "Continuity and Differentiability", slug: "continuity-and-differentiability" },
          { id: "ch-6", title: "Application of Derivatives", slug: "application-of-derivatives" },
          { id: "ch-7", title: "Integrals", slug: "integrals" },
          { id: "ch-8", title: "Application of Integrals", slug: "application-of-integrals" },
          { id: "ch-9", title: "Differential Equations", slug: "differential-equations" },
          { id: "ch-10", title: "Vector Algebra", slug: "vector-algebra" },
          { id: "ch-11", title: "Three Dimensional Geometry", slug: "three-dimensional-geometry" },
          { id: "ch-12", title: "Linear Programming", slug: "linear-programming" },
          { id: "ch-13", title: "Probability", slug: "probability" },
        ],
      },
      {
        id: "english",
        name: "English",
        bookName: "Flamingo",
        slug: "english",
        chapters: [
          { id: "ch-1", title: "The Last Lesson", slug: "the-last-lesson" },
          { id: "ch-2", title: "Lost Spring", slug: "lost-spring" },
          { id: "ch-3", title: "Deep Water", slug: "deep-water" },
          { id: "ch-4", title: "The Rattrap", slug: "the-rattrap" },
          { id: "ch-5", title: "Indigo", slug: "indigo" },
          { id: "ch-6", title: "Poets and Pancakes", slug: "poets-and-pancakes" },
          { id: "ch-7", title: "The Interview", slug: "the-interview" },
          { id: "ch-8", title: "Going Places", slug: "going-places" },
        ],
      },
    ],
  },
];

export function getClassData(level: number): NcertClass | undefined {
  return NCERT_SYLLABUS.find((c) => c.level === level);
}

export function getSubjectsForClass(level: number): NcertSubject[] {
  const classData = getClassData(level);
  return classData?.subjects ?? [];
}

export function getChaptersForSubject(classLevel: number, subjectId: string): NcertChapter[] {
  const subjects = getSubjectsForClass(classLevel);
  const subject = subjects.find((s) => s.id === subjectId);
  return subject?.chapters ?? [];
}
